# Import

In [5]:
import torch
import numpy as np

# 3.1 텐서 생성

In [2]:
print(torch.tensor([1, 2, 3]))
print(torch.Tensor([[1, 2, 3], [4, 5, 6]]))
print(torch.LongTensor([1, 2, 3]))
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


# 3.2 텐서 속성

In [3]:
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.8762, 0.3570]])
torch.Size([1, 2])
torch.float32
cpu


# 3.3 텐서 차원 변환

In [4]:
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape)

tensor([[0.2289, 0.6758]])
torch.Size([1, 2])
tensor([[0.2289],
        [0.6758]])
torch.Size([2, 1])


# 3.4 텐서 자료형 설정

In [5]:
tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)

tensor([[0.7365, 0.6395, 0.6307],
        [0.4247, 0.4115, 0.1165],
        [0.6340, 0.0942, 0.4023]])


# 3.5 텐서 GPU 장치 설정

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.tensor([1, 2, 3], dtype=torch.float, device=device)
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
print(gpu)
print(tensor)

cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.5365]], device='cuda:0')


# 3.6 텐서 장치 변환

In [4]:
cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to(device)
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


# 3.7 넘파이 배열의 텐서 변환

In [7]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


# 3.8 텐서의 넘파이 배열 변환

In [10]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float, device=device)
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
